# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 793)
        MainWindow.setStyleSheet("#widget_2{\n"
"image:url(:/images/keskinkimya-logo.png);\n"
"margin:2px;\n"
"padding:1px\n"
"\n"
"}\n"
"#midwidget{\n"
"background-color:#4f4e4d\n"
"}\n"
"#topwidget{\n"
"background-color:#F57A42\n"
"}\n"
"#logoutButton{\n"
"background-color:#4f4e4d;\n"
"color:#F57A42;\n"
"font-size:15px;\n"
"font-weight:bold; \n"
"}\n"
"#usernameLabel{\n"
"background-color:#4f4e4d;\n"
"color:#F57A42;\n"
"qproperty-alignment: AlignCenter;\n"
"\n"
"}\n"
"#selectedLabel{\n"
"color:#F57A42;\n"
"font-size:80px;\n"
"qproperty-alignment: AlignCenter;\n"
"}\n"
"#okButton,#notButton{\n"
"background-color:#4f4e4d;\n"
"color:#F57A42;\n"
"font-size:30px;\n"
"}\n"
"#listWidget{\n"
"background-color:#4f4e4d;\n"
"color:#F57A42;\n"
"border:1px solid #F57A42\n"
"}\n"
"#listWidget::item{\n"
"height:20px;\n"
"border:0.5px solid #F57A42;\n"
"padding:2px;\n"
"}\n"
"#line, #line_2{\n"
"background-color:#F57A42;\n"
"}\n"
"#confirmedLabel, #defectedLabel{\n"
"background-color:#F57A42;\n"
"\n"
"}\n"
"#backButton{\n"
"background-color:#F57A42;\n"
"color:#4f4e4d;\n"
"font-size:25px;\n"
"}\n"
"\n"
"\n"
"")
        
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.topwidget = QtWidgets.QWidget(self.centralwidget)
        self.topwidget.setGeometry(QtCore.QRect(0, 0, 801, 91))
        self.topwidget.setStyleSheet("")
        self.topwidget.setObjectName("topwidget")
        self.label = QtWidgets.QLabel(self.topwidget)
        self.label.setGeometry(QtCore.QRect(200, 10, 491, 81))
        font = QtGui.QFont()
        font.setFamily("HeiS")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(self.topwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 201, 91))
        self.widget_2.setMinimumSize(QtCore.QSize(201, 91))
        self.widget_2.setMaximumSize(QtCore.QSize(201, 91))
        self.widget_2.setStyleSheet("#widget_2{\n"
"image:url(:/images/keskinkimya-logo.png)\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.logoutButton = QtWidgets.QPushButton(self.topwidget)
        self.logoutButton.setGeometry(QtCore.QRect(690, 10, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("")
        self.logoutButton.setObjectName("logoutButton")
        self.usernameLabel = QtWidgets.QLabel(self.topwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(690, 50, 91, 31))
        self.usernameLabel.setStyleSheet("")
        self.usernameLabel.setObjectName("usernameLabel")
        self.midwidget = QtWidgets.QWidget(self.centralwidget)
        self.midwidget.setGeometry(QtCore.QRect(0, 90, 801, 681))
        self.midwidget.setStyleSheet("")
        self.midwidget.setObjectName("midwidget")
        self.selectedLabel = QtWidgets.QLabel(self.midwidget)
        self.selectedLabel.setGeometry(QtCore.QRect(150, 40, 621, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.selectedLabel.setFont(font)
        self.selectedLabel.setObjectName("selectedLabel")
        self.confirmedLabel = QtWidgets.QLabel(self.midwidget)
        self.confirmedLabel.setGeometry(QtCore.QRect(0, 10, 151, 31))
        
        self.confirmedLabel.setObjectName("confirmedLabel")
        self.listWidget = QtWidgets.QListWidget(self.midwidget)
        self.listWidget.setGeometry(QtCore.QRect(0, 180, 151, 461))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        
        self.line = QtWidgets.QFrame(self.midwidget)
        self.line.setGeometry(QtCore.QRect(0, 150, 801, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.defectedLabel = QtWidgets.QLabel(self.midwidget)
        self.defectedLabel.setGeometry(QtCore.QRect(0, 150, 151, 31))
        self.defectedLabel.setObjectName("defectedLabel")
        self.backButton = QtWidgets.QPushButton(self.midwidget)
        self.backButton.setGeometry(QtCore.QRect(0, 640, 151, 41))
        self.backButton.setObjectName("backButton")
        self.okButton = QtWidgets.QPushButton(self.midwidget)
        self.okButton.setGeometry(QtCore.QRect(160, 160, 621, 251))
        self.okButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon)
        self.okButton.setIconSize(QtCore.QSize(150, 150))
        self.okButton.setObjectName("okButton")
        self.notButton = QtWidgets.QPushButton(self.midwidget)
        self.notButton.setGeometry(QtCore.QRect(160, 430, 621, 241))
        self.notButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/laundry.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notButton.setIcon(icon1)
        self.notButton.setIconSize(QtCore.QSize(150, 150))
        self.notButton.setObjectName("notButton")
        self.line_2 = QtWidgets.QFrame(self.midwidget)
        self.line_2.setGeometry(QtCore.QRect(150, 410, 651, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#4f4e4d;\">Kiosk 1</span></p></body></html>"))
        self.logoutButton.setText(_translate("MainWindow", "LOG OUT"))
        self.usernameLabel.setText(_translate("MainWindow", "username"))
        self.selectedLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:52pt;\">Seçim Yapınız...</span></p></body></html>"))
        self.confirmedLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#4f4e4d;\">CONFIRMED</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "1234"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "1234"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "1234"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "1234"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "1234"))
        item = self.listWidget.item(5)
        item.setText(_translate("MainWindow", "12342"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.defectedLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#4f4e4d;\">DEFECTED</span></p></body></html>"))
        self.backButton.setText(_translate("MainWindow", "BACK"))
import resource_rc