# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class LoginEkran(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.setStyleSheet("#widget{\n"
"border-image:url(:/images/Başlıksız-1.png);\n"
"border-top-left-radius:50px;\n"
"border-bottom-right-radius:50px;\n"
"\n"
"}\n"
"\n"
"#lineEdit,#usernameText,#passwordText{\n"
"background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid #f3f3f3;\n"
"color:#f3f3f3;\n"
"padding-bottom:7px;\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 40, 721, 521))
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(370, 0, 365, 520))
        self.widget_2.setObjectName("widget_2")
        self.girisButton = QtWidgets.QPushButton(self.widget_2)
        self.girisButton.setGeometry(QtCore.QRect(190, 290, 101, 41))
        self.girisButton.setStyleSheet("#girisButton{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 227, 227, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(0,0,0,210);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"#girisButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 159, 33, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.girisButton.setObjectName("girisButton")
        self.cikisButton = QtWidgets.QPushButton(self.widget_2)
        self.cikisButton.setGeometry(QtCore.QRect(80, 290, 101, 41))
        self.cikisButton.setStyleSheet("#cikisButton{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(227, 227, 227, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color:rgba(0,0,0,210);\n"
"border-radius:5px;\n"
"\n"
"}\n"
"#cikisButton:hover{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 159, 33, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.cikisButton.setObjectName("cikisButton")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(80, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setFocus()
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setObjectName("lineEdit")
        self.usernameText = QtWidgets.QLineEdit(self.widget_2)
        self.usernameText.setGeometry(QtCore.QRect(80, 170, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.usernameText.setFont(font)
        self.usernameText.setObjectName("usernameText")
        self.passwordText = QtWidgets.QLineEdit(self.widget_2)
        self.passwordText.setGeometry(QtCore.QRect(80, 210, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.passwordText.setFont(font)
        self.passwordText.setObjectName("passwordText")
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.Password)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(50, 140, 21, 21))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/images/barcode.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 21, 21))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/team.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(50, 220, 21, 21))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/images/key.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.girisButton.setText(_translate("MainWindow", "LOG IN"))
        self.cikisButton.setText(_translate("MainWindow", "LOG OUT"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LoginEkran()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
